export const container: string;
export const headerNavigate: string;
export const Header: string;
export const header: string;
export const PageTitle: string;
export const pageTitle: string;
export const arrowBack: string;
export const identityForm: string;
export const submissionArea: string;
